### ISSUE TITLE
Switch to something else or enhance tinytag

### ISSUE THREAD

**Issue by aw-was-here** [whatsnowplaying/whats-now-playing#154]
TinyTag is just lacking some features and is a bit too unreliable around the edges. :frowning_face:

**Comment by aw-was-here** [comment]
Mutagen is GPL so that should be avoided.

**Comment by mathiascode** [comment]
> is a bit too unreliable around the edges. frowning_face

Anything left to be fixed in tinytag? I've contributed fixes for various audio formats that were released in tinytag 1.8.0+.

**Comment by aw-was-here** [comment]
The biggest missing bits for me are the acoustid id, musicbrainz related IDs, originalyear, and disc subtitle tags.  Basically, lots of metadata just isn't available in tinytag without having to add a lot of code. :( @mathiascode
