### ISSUE TITLE
🐛 Bug Report: Unplayed songs in local mode

### ISSUE THREAD

**Issue by evilsohn** [whatsnowplaying/whats-now-playing#347]
### 📜 Description

I'm using the app on a Mac. The program pulls every song as soon as I load it into a deck in Serato.
On PC it would only pull a song when I added volume to the particular deck (in that case the song would appear as played in Serato's history).
It seems the program is always pulling tracks as if "show unplayed tracks" has been enabled in Serato's history.

### 👟 Reproduction steps

I put a song into a deck in Serato on Mac. Then I press play to preview the song with the volume fader on that deck at 0%

### 👍 Expected behavior

Nothing. Since the song hasn't played with volume yet it doesn't show up in Serato's history, so it should get pulled to the text file.

### 👎 Actual Behavior

It get's pulled to the text file immediately or with the delay that I set up in the options.

### 💻 Operating system

MacOS

### 💻 Chipset/CPU

Apple M1

### 💻 Input source

Serato

**Comment by aw-was-here** [comment]
Interesting!  Was there a Serato version upgrade in the middle of the switch over?  I'm pretty sure I know what it is though.

**Comment by BinaryfxMEM** [comment]
Noticing this on Windows 11 running Serato 2.5.8.

Thanks for looking into this.

Awesome app by the way.

**Comment by aw-was-here** [comment]
Thanks!

My controller won't be back for at least another month but I have a fix in mind already.  I'll likely build you folks some test binaries to try out to see if my hunch is correct.

**Comment by aw-was-here** [comment]
Try the zip files attached to https://github.com/whatsnowplaying/whats-now-playing/actions/runs/1874634291 . They aren't cleaned up like the usually downloads, so if you have issues getting them unpacked, let me know and I'll clean them up. 

Thanks!

**Comment by speedyb22** [comment]
Grabbed the file from above, and it still seems to be an issue for me (Windows, Serato Pro 2.5.9)

**Comment by BinaryfxMEM** [comment]
do not see the zipped files.

**Comment by BinaryfxMEM** [comment]
problem still there.

**Comment by aw-was-here** [comment]
Just to make sure, none of you are using 'Newest' setting are you? If so, it will absolutely pull the latest track from the last deck touched.

**Comment by speedyb22** [comment]
Just tried it again.

"Newest" brings through the latest song, the second it's loaded, regardless of it being played or the volume being up.

"Oldest" appears to do the same, but for the 'previous' song, so to speak. I've had it not change a few times, and also once it presented a track which is in my library, however not one that wasn't in the past 20+ tracks loaded.

Attached video is of "oldest" being used when both the application and serato have been closed and re-opened...

https://user-images.githubusercontent.com/11336629/160669115-dd822373-d379-4814-9ed6-f36779042a32.mp4

Ideal behaviour would be for "newest" to only populate when the volume fader (or cross fader) are bought into play, meaning that track is actually playing out, similar to how the 'remote' option functions.

**Comment by aw-was-here** [comment]
> only populate when the volume fader (or cross fader) are bought into play

Last time I checked, Serato does not publish that information anywhere readable.  So assuming that is off the table, what solution do people propose?

**Comment by speedyb22** [comment]
The previous 1.4 version used to change only when a track is 'live', not sure how easy it would be to borrow whatever mechanism that was using as a trigger to then pull the track name / info using the current method?

I'd use the remote/live playlists option, but I always forget to enable it; it doesn't give the same level of detail (such as genre or bpm). It's also not a feature of Serato Lite, so it alienates some users.

Problem with having the latest track loaded is that shows a track before it's even been played. The user could also load in a track to have a quick listen, but change their mind (I often do this).

Having the oldest track can also become a problem if you've a playlist, or know 100% what you're playing next, and don't load it until the last minute before mixing, this would result in the previously (already played) track displaying for the majority of time the current track is playing. 

Even trying to create an overly convoluted checking system with track times and re-checking the playing deck, I can't really think of any ideal way to handle it without a trigger event.

**Comment by aw-was-here** [comment]
> The previous 1.4 version used to change only when a track is 'live'

It blew apart on anything with any complex filenames and definitely didn't always work when tracks were live.

**Comment by aw-was-here** [comment]
Likely fixed by #361

**Comment by aw-was-here** [comment]
Well, as fixed as it can be.  There are just limitations in what Serato 'publishes' to be read.

**Comment by aw-was-here** [comment]
Just published 3.0.1 which includes the changes that I think fix this issue as well as some other stuff.  Give it a whirl.  Thanks.

**Comment by speedyb22** [comment]
Just given it a quick test and with the 'Latest' setting selected, the text file doesn't update until I've either moved the cross fader onto a playing deck, or moved the volume fader up. That's the behaviour I'd expect.

**Comment by aw-was-here** [comment]
Thanks for the feedback!  I'm going to go ahead and close this one as fixed then.
