### ISSUE TITLE
🐛 Bug Report: no cover art from FLAC files

### ISSUE THREAD

**Issue by TIMOUNGEGE** [whatsnowplaying/whats-now-playing#395]
### 📜 Description

cover display works only mp3 and aif; but not flac. Is my setting or a bug?

### 👟 Reproduction steps

Play song Aif, mp3 and flac

### 👍 Expected behavior

Display covers in flac

### 👎 Actual Behavior

Titles in flac are ignored and there is no display of covers

### 💻 Operating system

Windows

### 💻 Chipset/CPU

Intel

### 💻 Input source

Serato

**Comment by aw-was-here** [comment]
Argh. I'm guessing one of the library updates broke FLAC.  Thanks. I'll take a look when I get a chance.

**Comment by aw-was-here** [comment]
Just tried to duplicate this one and I'm getting covers.

**Comment by aw-was-here** [comment]
To make sure it doesn't break in the future though, just added some tests for flac covers.  In the process, I did find that some metadata was getting missed.

**Comment by aw-was-here** [comment]
I'm going to close this one out.  Thanks!
