### ISSUE TITLE
🐛 Bug Report: Oldest / Newest

### ISSUE THREAD

**Issue by defmd** [whatsnowplaying/whats-now-playing#478]
### 📜 Description

I am not able to toggle between oldest and newest at version 3.1.0

### 👟 Reproduction steps

traybar - right click what's playing and trying to toggle between oldest newest (settings and pause are working fine)

### 👍 Expected behavior

switch between oldest / newest

### 👎 Actual Behavior

no change stays at newest

### 💻 Operating system

Windows

### 💻 Chipset/CPU

Intel

### 💻 Input source

Virtual DJ

### 🧱 Your Environment

i9 32gb gaming laptop

**Comment by aw-was-here** [comment]
Thanks!

Looks like a documentation/ease-of-use bug.  The m3u driver that is used for Virtual DJ doesn't support 'Oldest' thus why it won't let you set it to that.  (At some point, I'll likely build something that is 'deck aware' for Virtual DJ but that is a far future plan.)

So two things to try fix here:

1) Ideally, the newest/oldest options would get greyed out in the menu if those options aren't actually available (presently, both MPRIS2 and m3u drivers)

2) Documentation for m3u and MPRIS2 would specifically call out that only the 'Newest' option is used.

**Comment by aw-was-here** [comment]
Fixes for the above and a few other issues committed to the main branch.  Should appear in 3.1.1 which will likely get cut this week.  Thanks for the feedback @defmd !

**Comment by defmd** [comment]
thanks
