### ISSUE TITLE
OBS WebSockset support does not support newer OBS WebSocket v5 protocol

### ISSUE THREAD

**Issue by aw-was-here** [whatsnowplaying/whats-now-playing#509]
Decision needs to be made to either remove it or switch over to something different (https://github.com/aatikturk/obsws-python ?) or implement something custom since it appears our current OBS WS implementation is abandoned.

cc: @DachsbauTV

**Comment by DachsbauTV** [comment]
Hm would be a pity to drop it. Is there no way to migrate to websocket 5.0?

**Comment by aw-was-here** [comment]
It is just more a matter of effort. I'm not sure if anyone is even using the functionality.  That said, there are a few different OBS WS v5 python implementations so it may not be that hard after all.

**Comment by aw-was-here** [comment]
All of the implementations I'm finding are GPL 3.0. That's a huuuuuuge problem.

**Comment by aw-was-here** [comment]
Ok found one that is MIT: https://github.com/IRLToolkit/simpleobsws

**Comment by aw-was-here** [comment]
ok have the simpleobsws module working.  will need to do more intensive tests, but probably good enough to commit to main for now. The big gotcha is that _only_ v5 is supported.  The next release was likely going to make other breaking changes as well, but definitely something people will need to be aware of.

Thanks @DachsbauTV

**Comment by DachsbauTV** [comment]
haha absolutely no need to thank me :D thanks a lot to you!
