### ISSUE TITLE
🐛 Bug Report: building source missing serato as input

### ISSUE THREAD

**Issue by yakuv0** [whatsnowplaying/whats-now-playing#569]
### 📜 Description

By compiling source using builder.sh and launching app, serato doesn’t appear as an input.

### 👟 Reproduction steps

build using builder.sh

### 👍 Expected behavior

Serato support

### 👎 Actual Behavior

`Configured source Serato is not supported. Reconfiguring. `

### 💻 Operating system

MacOS

### 💻 Chipset/CPU

Intel

### 💻 Input source

Serato

**Comment by aw-was-here** [comment]
Is this a fresh install or an upgrade from an older version?

**Comment by yakuv0** [comment]
> Is this a fresh install or an upgrade from an older version?
> 
> (Also, might be worth mentioning that main right now is undergoing some _major_, incompatible changes, not all of which are documented yet. More things are bound to break...)

It’s a fresh install, also might be worth to mention other bugs faced in NowPlaying.spec to specify bundle version, etc and handled it by assigning it manually.

will check previous versions.
Much appreciations!

**Comment by yakuv0** [comment]
Would you mind sharing the serato test environment?!
Registering entries varies from controller to software though, didn’t get to test in DVS mode or on cdjs.

**Comment by aw-was-here** [comment]
> It’s a fresh install, also might be worth to mention other bugs faced in NowPlaying.spec to specify bundle version, etc and handled it by assigning it manually.

Hmm...  python 3.10 is in use, correct?  Serato plugin absolutely requires 3.10+.  That pop-up window is a a very new code path soooo ... likely buggy.  😄  But let's make sure that we cover the relatively easy things first.

**Comment by yakuv0** [comment]
@aw-was-here [Latest (3.1.2)](https://github.com/whatsnowplaying/whats-now-playing/releases/tag/3.1.2)  didn’t have serato, [(3.1.0)](https://github.com/whatsnowplaying/whats-now-playing/releases/tag/3.1.0) has it.
would appreciate considering a fix in next releases.

**Comment by aw-was-here** [comment]
> Would you mind sharing the serato test environment?! Registering entries varies from controller to software though, didn’t get to test in DVS mode or on cdjs.

https://github.com/whatsnowplaying/whats-now-playing/blob/main/.github/workflows/testing.yaml covers how the software is tested at the PR level. The input data sources (built from when I had Serato 2.5 installed) are in tests/serato-2.x/*  My own "real world usage" setup is Serato 2.6.x w/a Roland DJ-202 on macOS 12.6.x.  I've also got a Windows and Linux box setup to do some on the fly checking.

**Comment by aw-was-here** [comment]
> @aw-was-here [Latest (3.1.2)](https://github.com/whatsnowplaying/whats-now-playing/releases/tag/3.1.2) didn’t have serato, [(3.1.0)](https://github.com/whatsnowplaying/whats-now-playing/releases/tag/3.1.0) has it. would appreciate considering a fix in next releases.

Something else isn't building correctly if Serato shows up in 3.1.0 but not in 3.1.2.  Does a binary release work?

**Comment by yakuv0** [comment]
> Hmm... python 3.10 is in use, correct? Serato plugin absolutely requires 3.10+. That pop-up window is a a very new code path soooo ... likely buggy. 😄 But let's make sure that we cover the relatively easy things first.

python3.9 on conda, actually didn’t get to see the pop-up window yet.
Here what it was for the bundleversion
`  File "NowPlaying.spec", line 156, in <module>
    'CFBundleShortVersionString': getcfbundleshortversionstring(),
  File "NowPlaying.spec", line 70, in getcfbundleshortversionstring
    short = '.'.join(getsplitversion()[0:3])
  File "NowPlaying.spec", line 50, in getsplitversion
    if '-' in versionparts[2]:
IndexError: list index out of range`

**Comment by aw-was-here** [comment]
> python3.9 on conda

OK, yeah, all kinds of things are going to break on 3.9.

**Comment by yakuv0** [comment]
> Something else isn't building correctly if Serato shows up in 3.1.0 but not in 3.1.2. Does a binary release work?

Yh, binary releases has it.
> Also, you can see how the binaries are built here: https://github.com/whatsnowplaying/whats-now-playing/blob/main/.github/workflows/pyinstaller.yaml . The stuff hanging off releases are usually just a bit of re-zipping/renaming.
Legend 🙌

**Comment by aw-was-here** [comment]
I'll add some code to make sure people are building with a supported version of Python to prevent this confusion. 👍  Thanks for the bug report!

**Comment by aw-was-here** [comment]
(FWIW, I'd expect 3.1.2 to work with Python 3.9 as well so that's a bit surprising.)

**Comment by yakuv0** [comment]
@aw-was-here Sucha pleasure.
Nowplaying registers real time on fader up! 
Hail to that 🙌
