### ISSUE TITLE
Workflow: export list

### ISSUE THREAD

**Issue by yakuv0** [whatsnowplaying/whats-now-playing#571]
### 📜 Description

Exit session without loading tracks
`  File "nowplaying/trackpoll.py", line 95, in run
    self.create_setlist()
  File "nowplaying/trackpoll.py", line 381, in create_setlist
    max_artist_size = max(len(t['artist']) for t in previoustrack)
ValueError: max() arg is an empty sequence `

### 👟 Reproduction steps

Serato launched with new session
Launch nowplaying
Exit without loading tracks

### 👍 Expected behavior

Being aware that this doesn’t effect the functionality for now, having an export option in menus icon would come real useful specially if having now playing always in menu bar

### 👎 Actual Behavior

Only exports setlist on exit
the default system quit results in ‘Abort trap:6’ And no setlist exported

### 💻 Operating system

MacOS

### 💻 Chipset/CPU

Intel

### 💻 Input source

Serato

**Comment by aw-was-here** [comment]
I thought I tested that but I guess not. Thanks for the bug report!

**Comment by yakuv0** [comment]
No worries
Much appreciations
