### ISSUE TITLE
How to make a simple webserver request returning json?

### ISSUE THREAD

**Issue by ElToberino** [whatsnowplaying/whats-now-playing#728]
Hello,
first of all thanks a lot for this great software.
I wonder if (or how) it is possible to make a simple webserver request that is only returning a json file and not html.
I'm not very familiar with python and so my efforts to get behind the code couldn't answer this question.

Background:
I want to make a webserver request (from an ESP) returning only a simple json file (containing artist, title etc.) that I can process in my program.

Thanks for your help and best regards!

**Comment by ElToberino** [comment]
Thank you, that sounds good. I look forward to using the API with my program.

**Comment by aw-was-here** [comment]
OK, finally got the showstopper bug in 4.0.3 dealt with I believe.  So the REST API changes that went in with #729 should be available in a binary release now. 😄

**Comment by aw-was-here** [comment]
Closing this one out...
